# vim: nofoldenable: list:
# PIVARD Julien
# Dernière modification : Jeudi 23 décembre[12] 2021

###############
# Partie Fixe #
###############

GPR		= build.gpr

CHEMIN_OBJET	= obj
CHEMIN_RESLT	= bin
CHEMIN_ALI	= ali
RESLT_COMPIL	= ./bin/$(MODE)/$(CHOISIR_ALGO_DE_RESOLUTION)/executable

#############################################
# Les modifications sont à faire en dessous #
#############################################

# Permet de choisir le format de la documentation
FORMAT		= html

# Fixer le nom de l'application
NOMAPP		= Algorithme Évolutionnaire

# Pour activer le mode debug mettre à true
# ACTIVER_DEBUG = [true|false]
ACTIVER_DEBUG	= true

# Pour activer le mode verbeux
# ACTIVER_VERB = [true|false]
ACTIVER_VERB	= false

# Pour activer le mode strict
# ACTIVER_STRICT = [true|false]
ACTIVER_STRICT	= false

# Pour activer le traitement des avertissements comme si c'était des erreurs
# ACTIVER_WARN_SONT_ERREURS = [true|false]
ACTIVER_WARN_SONT_ERREURS	= false

# Active l'affichage dynamique de l'utilisation de la stack.
# ACTIVER_AFFICHER_LA_STACK = [true|false]
ACTIVER_AFFICHER_LA_STACK	= false

# Active l'affichage de l'ordre d'élaboration de paquets choisi
# par le compilateur.
# ACTIVER_AFFICHER_ORDRE_ELABORATION = [true|false]
ACTIVER_AFFICHER_ORDRE_ELABORATION	= false

# -l Montre le chemin complet du fichier désigné
# --show-rule Ajoute le nom de la règle qui à déclenché le signalement
# -o gnatcheck.out Pour désigner un fichier de sortie
# -dd affiche la progression
OPT_CHECK	= -dd -l -U --show-rule

# 0 = le plus rapide; 4 = le plus puissant.
NIVEAU_PREUVE	= 2

# Affichage des messages durant les preuves.
AFFICHAGE_MESSAGES	= fail
#  . fail       - N'affiche que les erreurs (default).
#  . all        - Affiche tous les résultats de gnatprove.
#  . provers    - Pareil que all, mais avec les info d'usage du prover.
#  . statistics - Pareil que provers, mais avec les temps et info d'étapes.

# éléments examiné pour la preuve
MODE_EXECUTION_PREUVE	= all
#  . check             - Vérification partiel et rapide des contraintes SPARK.
#  . check_all, stone  - Vérification complète des contraintes SPARK.
#  . flow, bronze      - Prouve que l'initialisation et le flot de données sont correct.
#  . prove             - Prouve l'absence d'erreurs d'exécution et de contrat
#  . all, silver, gold

# Fixer les arguments qui seront donné en entré de l'application
# lors de l'exécution
ARGUMENTSAPPLI	=

# Emplacement des binaires si ils ne sont pas localisable par les makefile
GNAT_BIN_PERSO	=

# Emplacement des sources
DOSSIERSRC	= src

# Choisi l'algo de résolution de l'évolution de la population
# CHOISIR_ALGO_DE_RESOLUTION = [seq|parallele]
CHOISIR_ALGO_DE_RESOLUTION	= parallele
